ALTER TABLE parse_jobs
  ADD COLUMN IF NOT EXISTS progress SMALLINT NOT NULL DEFAULT 0
    CHECK (progress BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS progress_message TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

